# server config
server:
  port: 8080
  servlet:
    context-path: /api
  api:
    version: "v1"


logging:
  level:
    root: info
    com.musinsa.shop: debug


# h2(inmemory) database config
spring:
  application:
    name: musinsa
  datasource:
    url: jdbc:log4jdbc:h2:mem:shop;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: musinsa
    password: mu12!@
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: h2
    generate-ddl: off
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none